export const projectData = {
  "3LINES": {
    projectTitle: "3Lines UI",
    strategy: ["Clean Code", "Security"],
    client: "3lines",
    technology: "ReactJS",
    projectDesc:
      "I contributed over 60% to the development of this project, collaborating with a 3-member team to build a complex UI with ShadCN UI and animations. The project included a detailed KYC process approved by the Super Admin for various business types. I integrated a ticketing system with WebSocket-based live chat and real-time notifications for actions like KYC submission, service purchases, and insurance logs. Additional features included merchant management, provider priority, service logs, and multi-role functionalities for Super Admin, Admin, Distributor, Retailer, and Sub-Retailer users.",
    images: [
      "cpd/1.PNG",
      "cpd/2.PNG",
      "cpd/3.PNG",
      "cpd/4.PNG",
      "cpd/5.PNG",
      "cpd/6.PNG",
      "cpd/7.PNG",
    ],
    openProject: true,
    openProjectLink: "https://companydev.cpd.net.in/login",
    viewCode: false,
    viewCodeLink: "",
    category: "Web Development",
  },
  CPD: {
    projectTitle: "CPD API Server",
    strategy: ["Provider Priority", "Secure APIs"],
    client: "CPD",
    technology: "ReactJS, TypeScript",
    projectDesc:
      "Developed a frontend interface for the CPD API Server with 90% ownership, focusing on monitoring API services, service logs, security logs, and user actions. Implemented functionalities for configuring providers, managing commissions, and adjusting API pricing, with KYC approval handled by the Super Admin.",
    images: [
      "apiserver/1.PNG",
      "apiserver/2.PNG",
      "apiserver/3.PNG",
      "apiserver/4.PNG",
      "apiserver/5.PNG",
      "apiserver/6.PNG",
      "apiserver/7.PNG",
      "apiserver/8.PNG",
      "apiserver/9.PNG",
    ],
    openProject: true,
    openProjectLink: "https://apiserverdev.cpd.net.in/login",
    viewCode: false,
    viewCodeLink: "",
    category: "Web Development",
  },
  EMAILAPI: {
    projectTitle: "Email API UI",
    strategy: ["Scalability", "Reliability"],
    client: "Internal",
    technology: "ReactJS",
    projectDesc:
      "Designed and developed a scalable email API service, allowing clients to send transactional and bulk emails. Included features for template management, email tracking, and real-time delivery reports.",
    images: ["emailapi/1.PNG", "emailapi/2.PNG", "emailapi/3.PNG"],
    openProject: true,
    openProjectLink: "https://emailserviceapi.vercel.app/",
    viewCode: false,
    viewCodeLink: "",
    category: "Web Development",
  },
  FININFOLIB: {
    projectTitle: "Fininfolib",
    strategy: ["Data Accuracy", "Employee Management"],
    client: "Internal",
    technology: "ReactJS, NextJS API",
    projectDesc:
      "Improved the company website by adding a robust HR dashboard and employee management system, including features like login, leave tracking, and detailed employee data management. Implemented data visualization with charts and filters for enhanced performance and analytics.",
    images: ["fininfolib/1.PNG"],
    openProject: true,
    openProjectLink: "https://fininfolib.vercel.app/",
    viewCode: false,
    viewCodeLink: "",
    category: "Web Development",
  },
  DHOOTHA: {
    projectTitle: "Dhootha Promotions",
    strategy: ["Product Reach", "User Engagement"],
    client: "Prem Varma",
    technology: "ReactJS",
    projectDesc:
      "Developed a promotional website to enhance product visibility and engagement among users. Implemented dynamic content and responsive design to effectively showcase offerings and improve reach.",
    images: ["dhootha/1.PNG"],
    openProject: true,
    openProjectLink: "https://www.doothapromotions.com/",
    viewCode: false,
    viewCodeLink: "",
    category: "Web Development",
  },
  FRESHSLICE: {
    projectTitle: "FreshSlice Food Ordering",
    strategy: ["User Experience", "Payment Integration"],
    client: "Internal",
    technology: "ReactJS, Stripe API",
    projectDesc:
      "Developed a responsive food ordering platform with features like real-time menu updates, order tracking, and payment gateway integration using Stripe.",
    images: ["freshslice/1.PNG", "freshslice/2.PNG", "freshslice/3.PNG"],
    openProject: false,
    openProjectLink: "",
    viewCode: true,
    viewCodeLink: "https://github.com/afriddev/freshslice",
    category: "Web Development",
    mobileView: true,
  },
  EMAILSENDER: {
    projectTitle: "Email Sender Library",
    strategy: ["Integration", "Minimal Code"],
    client: "Internal",
    technology: "Python, FastAPI",
    projectDesc:
      "Published a library on Dart's pub.dev, Python's PyPI, and npm for seamless email service integration. Designed to enable developers to integrate mail services into applications with minimal code and configuration.",
    images: [],
    openProject: false,
    openProjectLink: "",
    viewCode: true,
    viewCodeLink: "https://github.com/afriddev/emailAPI",
    category: "Open Source Contribution",
  },
  APP: {
    projectTitle: "Mobile App Development",
    strategy: ["Performance", "Design"],
    client: "Ammerunisa",
    technology: "Flutter, Dart,Firebase",
    projectDesc:
      "Developed multiple mobile applications for clients, focusing on sleek UI, smooth performance, and seamless integration with Firebase and MongoDB.",
    images: ["mainapp.png"],
    openProject: false,
    openProjectLink: "",
    viewCode: true,
    viewCodeLink: "https://github.com/afriddev/ameerunisa-tailors",
    category: "App Development",
    mobileView: true,
  },
  FASTAPI: {
    projectTitle: "FastAPI",
    strategy: ["Integration", "Minimal Code"],
    client: "Internal",
    technology: "FastAPI",
    projectDesc:
      "Published a library on Dart's pub.dev, Python's PyPI, and npm for seamless email service integration. Designed to enable developers to integrate mail services into applications with minimal code and configuration.",
    images: [
      "emailapihost/dart.PNG",
      "emailapihost/npm.PNG",
      "emailapihost/python.PNG",
    ],
    openProject: false,
    openProjectLink: "",
    viewCode: true,
    viewCodeLink: "https://github.com/afriddev/emailservice",
    category: "Open Source Contribution",
  },
  TAILORINGAPI: {
    projectTitle: "Tailoring API System",
    strategy: ["Customization", "Integration"],
    client: "Ameerunisa",
    technology: "Express.js, Firebase, MongoDB",
    projectDesc:
      "Developed a backend API for managing tailoring services, including order processing, customizations, and delivery tracking. Integrated Firebase for notifications and MongoDB for efficient data storage and retrieval.",
    images: [],
    openProject: false,
    openProjectLink: "",
    viewCode: true,
    viewCodeLink: "https://github.com/afriddev/aaaTailors-mongo_api",
    category: "API Development",
  },
  FININFOLIBAPI: {
    projectTitle: "fininfolib API",
    strategy: ["Data Accuracy", "Scalability"],
    client: "Internal",
    technology: "Next.js, MongoDB",
    projectDesc:
      "Built a backend API to manage and analyze financial data with advanced filtering and analytics features. Ensured robust performance and scalability for large-scale datasets using MongoDB.",
    images: [],
    openProject: false,
    openProjectLink: "",
    viewCode: true,
    viewCodeLink: "https://github.com/afriddev/fininfolib",
    category: "API Development",
  },
};
